/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab3;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 98tae
 */
public class SwigSinhVien extends javax.swing.JFrame {

    private DAO list;

    /**
     * Creates new form SwigSinhVien
     */
    public SwigSinhVien() {
        initComponents();
        list = new QLSV();
        list.insert(new SINHVIEN("meo", 10, "Ứng Dụng Phầm Mềm", "True"));
        DisplayTable();
        ClearForm();
        txtHocLuc.setEditable(false);
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbbNganh = new javax.swing.JComboBox<>();
        cbPT = new javax.swing.JCheckBox();
        btnThem = new javax.swing.JToggleButton();
        btnSua = new javax.swing.JToggleButton();
        btnXoa = new javax.swing.JToggleButton();
        btnReset = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtHocLuc = new javax.swing.JTextField();
        btnSXTT = new javax.swing.JButton();
        btnSXTD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel2.setText("HỌ VÀ TÊN");

        jLabel3.setText("ĐIỂM");

        jLabel4.setText("NGÀNH");

        cbbNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ứng Dụng Phần Mềm", "Thiết Kế Trang Web", " " }));

        cbPT.setText("Có Phần Thưởng ?");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setText("Nhập Mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ Và Tên", "Điểm", "Ngành", "Học Lực", "Thưởng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);

        jLabel5.setText("HỌC LỰC");

        btnSXTT.setText("Sắp Xếp Theo Tên");
        btnSXTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXTTActionPerformed(evt);
            }
        });

        btnSXTD.setText("Sắp Xếp Theo Điểm");
        btnSXTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXTDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPT)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(txtDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                                .addComponent(cbbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(27, 27, 27)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnSXTT)
                        .addGap(18, 18, 18)
                        .addComponent(btnSXTD)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtHocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(cbPT)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnReset))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSXTT)
                    .addComponent(btnSXTD))
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         if(txtName.getText().equals("") && txtDiem.getText().equals("")){
            JOptionPane.showMessageDialog(this, " không đc để trống");}
        else if (txtName.getText().equals("") || txtDiem.getText().equals("")){
            JOptionPane.showMessageDialog(this, " không được để trống tên hoặc điểm");   
        }
        else 
        {
        String Nameadd = txtName.getText();
        String Diemadd = txtDiem.getText();
        String Nganhadd = (String) cbbNganh.getSelectedItem();
        String PTADD = "";
        if (cbPT.isSelected() == true) {
            PTADD = "True";
        } else {
            PTADD = "False";
        }
        list.insert(new SINHVIEN(Nameadd, Float.parseFloat(Diemadd), Nganhadd, PTADD));
        JOptionPane.showMessageDialog(this, "Thêm mới thành công");
        DisplayTable();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
    if(txtName.getText().equals("") && txtDiem.getText().equals("")){
            JOptionPane.showMessageDialog(this, " không có gì để sửa");}
        else 
        {
        
        
        int viTri = this.tblSinhVien.getSelectedRow();
        if (viTri == -1) {
            return;
        }
        String hoTen = txtName.getText();
        float diem = Float.parseFloat(txtDiem.getText());
        String Nganh = (String) cbbNganh.getSelectedItem();
        String Thuong = "";
        if (cbPT.isSelected() == true) {
            Thuong = "true";
        } else {
            Thuong = "false";
        }
        this.list.Update(viTri, new SINHVIEN(hoTen, diem, Nganh, Thuong));
        DisplayTable();
        JOptionPane.showMessageDialog(this, "sửa thành công");
        ClearForm();
    }//GEN-LAST:event_btnSuaActionPerformed
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    if(txtName.getText().equals("") && txtDiem.getText().equals("")){
            JOptionPane.showMessageDialog(this, " không có gì để xóa");}
        else 
        {
        
        int showmess =   JOptionPane.showConfirmDialog(this, " bạn có muốn xóa");
        if(showmess == JOptionPane.YES_OPTION){}
        else if (showmess == JOptionPane.NO_OPTION){
        return;
        }  else if (showmess == JOptionPane.CANCEL_OPTION){
        return;}
        
        int index = this.tblSinhVien.getSelectedRow();
        if (index == -1) {
            return;
        }

        this.list.Delete(index);

        DisplayTable();
        ClearForm();

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        ClearForm();
        JOptionPane.showMessageDialog(this, "Nhập Mới");
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        int viTri = this.tblSinhVien.getSelectedRow();
        if (viTri == -1) {
            return;
        }
        SINHVIEN sv = this.list.getList().get(viTri);
        txtName.setText(sv.getHoTen());
        txtHocLuc.setText(sv.getGrade());
        String dieme = String.valueOf(sv.getDiem());
        txtDiem.setText(dieme);
        if (sv.getThuong().equalsIgnoreCase("true")) {
            cbPT.setSelected(true);
        } else {
            cbPT.setSelected(false);
        }

    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnSXTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXTTActionPerformed
        this.list.SXNAME();
        DisplayTable();
        JOptionPane.showMessageDialog(this, "Đã Sắp Xếp Xong");
    }//GEN-LAST:event_btnSXTTActionPerformed

    private void btnSXTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXTDActionPerformed
       this.list.SXDIEM();
        DisplayTable();
        JOptionPane.showMessageDialog(this, "Đã Sắp Xếp Xong");
    }//GEN-LAST:event_btnSXTDActionPerformed

    public void ClearForm() {
        txtName.setText("");
        txtDiem.setText("");
        txtHocLuc.setText("");
        cbbNganh.setSelectedIndex(0);
        cbPT.setSelected(false);
    }

    public void DisplayTable() {
        DefaultTableModel dtm = (DefaultTableModel) this.tblSinhVien.getModel();
        dtm.setRowCount(0);
        ArrayList<SINHVIEN> ds = list.getList();
        for (int i = 0; i < ds.size(); i++) {
            SINHVIEN sv = ds.get(i);        
            Object[] rowData = new Object[]{
                sv.getHoTen(),
                sv.getDiem(),
                sv.getNganh(),
                sv.getGrade(),
                sv.getThuong(),};

            dtm.addRow(rowData);

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwigSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwigSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwigSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwigSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwigSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnReset;
    private javax.swing.JButton btnSXTD;
    private javax.swing.JButton btnSXTT;
    private javax.swing.JToggleButton btnSua;
    private javax.swing.JToggleButton btnThem;
    private javax.swing.JToggleButton btnXoa;
    private javax.swing.JCheckBox cbPT;
    private javax.swing.JComboBox<String> cbbNganh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHocLuc;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
